serviceAccount: projects/${PROJECT_ID}/serviceAccounts/cloudbuild-builder-sa@${PROJECT_ID}.iam.gserviceaccount.com
steps:
  # Step 0: Build App Docker image (using GCR instead of Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'
      - '.'
    dir: .

  # Step 1: Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Docker Image
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}'
    waitFor:
      - Build Docker Image

  # Step 2: Deploy updated image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: Deploy to Cloud Run
    args:
      - '-c'
      - |-
        set -e
        gcloud run deploy ${_SERVICE_NAME} \
          --image gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars AUTH_PROVIDER=firestore,AUTH_API_TIMEOUT=10000,CHATAI_API_URL=https://europe-west2-wa-aichat-test.cloudfunctions.net/api,CHATAI_API_TIMEOUT=10000,FIREBASE_AUTH_EMAIL=abdulrahim.klis+11@ext.leadtech.com,FIREBASE_AUTH_PASSWORD=123456Aa!!,CORS_ORIGIN=https://leadtech-crm-110642273202.europe-west1.run.app,FIRESTORE_DATABASE_ID=crm-aichat-database,GCP_TYPE=service_account,GCP_PROJECT_ID=${PROJECT_ID},GCP_CLIENT_EMAIL=nest-firestore@webapps-crm-dev.iam.gserviceaccount.com,GCP_CLIENT_ID=117186042533594047944,GCP_AUTH_URI=https://accounts.google.com/o/oauth2/auth,https://accounts.google.com/o/oauth2/auth=https://oauth2.googleapis.com/token,GCP_AUTH_PROVIDER_X509_CERT_URL=https://www.googleapis.com/oauth2/v1/certs,https://www.googleapis.com/oauth2/v1/certs=https://www.googleapis.com/robot/v1/metadata/x509/nest-firestore%40webapps-crm-dev.iam.gserviceaccount.com,GCP_UNIVERSE_DOMAIN=googleapis.com,GCP_LOG_NAME=leadtech-crm,JWT_SECRET=leadtech-crm-jwt-secret-key-change-in-production,JWT_ACCESS_EXPIRES_IN=3600,JWT_REFRESH_EXPIRES_IN=604800,DEFAULT_USER_EMAIL=abdulrahim.klis@ext.leadtech.com,DEFAULT_USER_PASSWORD=123456Aa!! \
          --set-secrets GCP_PRIVATE_KEY=GCP_PRIVATE_KEY:latest,GCP_PRIVATE_KEY_ID=GCP_PRIVATE_KEY_ID:latest,FIREBASE_WEB_API_KEY=FIREBASE_WEB_API_KEY:latest
    entrypoint: bash
# Substitution variables (can be overridden in trigger configuration)
substitutions:
  # _ENVIRONMENT: staging
  _SERVICE_NAME: leadtech-crm
  _ARTIFACT_REPO: leadtech-crm
  _REGION: europe-west2
  # Environment variables for Cloud Run
  _VITE_API_URL: ""

# Use Cloud Logging to store the logs from the execution
options:
  logging: CLOUD_LOGGING_ONLY
