steps:
  # Step 0: Build App Docker image (using GCR instead of Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker Image
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest'
      - '.'
    dir: .

  # Step 1: Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Docker Image
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}'
    waitFor:
      - Build Docker Image

  # Step 2: Deploy updated image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: Deploy to Cloud Run
    args:
      - '-c'
      - |-
        set -e
        gcloud run deploy ${_SERVICE_NAME} \
          --image gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest \
          --region ${_REGION} \
          --platform managed \
          --service-account cloudrun-runtime-sa@${PROJECT_ID}.iam.gserviceaccount.com \
          --allow-unauthenticated \
          --set-env-vars AUTH_PROVIDER=firestore \
          --set-env-vars AUTH_API_TIMEOUT=10000 \
          --set-env-vars CHATAI_API_URL=https://europe-west2-wa-aichat-test.cloudfunctions.net/api \
          --set-env-vars CHATAI_API_TIMEOUT=10000 \
          --set-env-vars FIREBASE_AUTH_EMAIL=abdulrahim.klis+11@ext.leadtech.com \
          --set-env-vars FIREBASE_AUTH_PASSWORD=123456Aa!! \
          --set-env-vars CORS_ORIGIN=https://crm-933097676674.europe-west2.run.app \
          --set-env-vars FIRESTORE_DATABASE_ID=crm-aichat-database \
          --set-env-vars GCP_TYPE=service_account \
          --set-env-vars GCP_PROJECT_ID=${PROJECT_ID} \
          --set-env-vars GCP_CLIENT_EMAIL=nest-firestore@${PROJECT_ID}.iam.gserviceaccount.com \
          --set-env-vars GCP_CLIENT_ID=117186042533594047944 \
          --set-env-vars GCP_AUTH_URI=https://accounts.google.com/o/oauth2/auth \
          --set-env-vars GCP_TOKEN_URI=https://oauth2.googleapis.com/token \
          --set-env-vars GCP_AUTH_PROVIDER_X509_CERT_URL=https://www.googleapis.com/oauth2/v1/certs \
          --set-env-vars GCP_CLIENT_X509_CERT_URL=https://www.googleapis.com/robot/v1/metadata/x509/nest-firestore%40${PROJECT_ID}.iam.gserviceaccount.com \
          --set-env-vars GCP_UNIVERSE_DOMAIN=googleapis.com \
          --set-env-vars GCP_LOG_NAME=leadtech-crm \
          --set-env-vars JWT_SECRET=leadtech-crm-jwt-secret-key-change-in-production \
          --set-env-vars JWT_ACCESS_EXPIRES_IN=3600 \
          --set-env-vars JWT_REFRESH_EXPIRES_IN=604800 \
          --set-env-vars DEFAULT_USER_EMAIL=abdulrahim.klis@ext.leadtech.com \
          --set-env-vars DEFAULT_USER_PASSWORD=123456Aa!! \
          --set-secrets GCP_PRIVATE_KEY=GCP_PRIVATE_KEY:latest \
          --set-secrets GCP_PRIVATE_KEY_ID=GCP_PRIVATE_KEY_ID:latest \
          --set-secrets FIREBASE_WEB_API_KEY=FIREBASE_WEB_API_KEY:latest

    entrypoint: bash
# Substitution variables (can be overridden in trigger configuration)
substitutions:
  # _ENVIRONMENT: staging
  _SERVICE_NAME: leadtech-crm
  _ARTIFACT_REPO: leadtech-crm
  _REGION: europe-west2
  # Environment variables for Cloud Run
  _VITE_API_URL: ""

# Use Cloud Logging to store the logs from the execution
options:
  logging: CLOUD_LOGGING_ONLY
